# -*- coding: utf-8 -*-
"""ДЗ3_Тоболовська Євгенія.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1smzwbVghDyNUBdy-DdffUDv6Ip_TOGSj

Завдання 1
"""

import os
import shutil
from pathlib import Path

def copy_files(src, dst):
    for item in os.listdir(src):
        item_path = Path(src) / item
        if item_path.is_dir():
            # Якщо елемент є директорією, рекурсивно викликаємо функцію
            copy_files(item_path, dst)
        else:
            # Визначаємо піддиректорію на основі розширення файлу
            subdir_name = item_path.suffix[1:]  # видаляємо крапку з розширення
            if not subdir_name:
                subdir_name = 'no_extension'
            subdir_path = Path(dst) / subdir_name
            subdir_path.mkdir(parents=True, exist_ok=True)
            # Копіюємо файл
            shutil.copy(item_path, subdir_path)

source_path = '/content/drive/My Drive/source_folder'
destination_path = '/content/drive/My Drive/destination_folder'

try:
    copy_files(source_path, destination_path)
except Exception as e:
    print(f"Помилка: {e}")

"""Завдання 2"""

import turtle

def koch_curve(t, order, size):
    """
    Функція для малювання кривої Коха.
    t - об'єкт turtle.
    order - рівень рекурсії.
    size - довжина лінії.
    """
    if order == 0:
        t.forward(size)
    else:
        for angle in [60, -120, 60, 0]:
            koch_curve(t, order-1, size/3)
            t.left(angle)

def koch_snowflake(t, order, size):
    """
    Функція для малювання сніжинки Коха.
    """
    for _ in range(3):
        koch_curve(t, order, size)
        t.right(120)

# Налаштування вікна turtle
window = turtle.Screen()
window.bgcolor("white")

# Створення об'єкта turtle
t = turtle.Turtle()
t.color("blue")

# Встановлення швидкості
t.speed(0)

# Визначення рівня рекурсії
recursion_level = int(input("Введіть рівень рекурсії для сніжинки Коха: "))

# Малюємо сніжинку Коха
koch_snowflake(t, recursion_level, 300)

# Завершення роботи turtle при кліку
window.exitonclick()